#OpenVPN
openvpn_base_path: "/etc/openvpn"
openvpn_config_server_path: "{{ openvpn_base_path }}/server"
openvpn_config_client_path: "{{ openvpn_base_path }}/client"


#Easy-rsa
easy_rsa_pki_suppr: "no"
easy_rsa_base_path: "/usr/share/easy-rsa/3"
easy_rsa_script: "{{ easy_rsa_base_path }}/easyrsa"
easy_rsa_ca_password: "your_password"

# CA Parameters
key_cn: "ca@{{ ansible_hostname }}"
key_country: "US"
key_province: "NY"
key_city: "New York"
key_organisation: "EvilCorp"
key_mail: "evilcorp@foo.com"
key_ou: "evilcorp room"
key_size: 2048
