#OpenVPN
openvpn_base_path: "/etc/openvpn"

#Easy-rsa
easy_rsa_pki_suppr: "no"
easy_rsa_base_path: "/usr/share/easy-rsa/3"
easy_rsa_script: "{{ easy_rsa_base_path }}/easyrsa"

# CA Parameters
key_size: 2048
key_country: "US"
key_province: "NY"
key_city: "New York"
key_organisation: "BlackOut"
key_mail: "blackout@foo.com"
key_ou: "blackout"
key_name: "server"
