#OpenVPN
openvpn_base_path: "/etc/openvpn"
openvpn_config_server_path: "{{ openvpn_base_path }}/server"
openvpn_config_client_path: "{{ openvpn_base_path }}/client"
##Necessaries variables for openvpn server conf file
openvpn_ca: "ca.crt"
openvpn_server_key: "{{ ansible_hostname }}.key"
openvpn_server_crt: "{{ ansible_hostname }}.crt"
openvpn_diffie_hellman_key: "dh.pem"
openvpn_hmac_key: "ta.key"
openvpn_port: 1194
openvpn_max_clients_on_server: 4
openvpn_first_dns: 8.8.4.4
openvpn_second_dns: 8.8.8.8
openvpn_server_subnet: 10.0.8.0 
openvpn_route: 
  - { subnet: 192.168.0.0, netmask: 255.255.255.0 }
  - { subnet: 192.168.1.0, netmask: 255.255.255.0 }

#Easy-rsa
easy_rsa_pki_suppr: "no"
easy_rsa_pki_path: "{{ lookup('env', 'HOME') }}/pki"
easy_rsa_base_path: "/usr/share/easy-rsa/3"
easy_rsa_script: "{{ easy_rsa_base_path }}/easyrsa"
easy_rsa_ca_password: "your_password"

# CA Parameters
key_cn: "ca@{{ ansible_hostname }}"
key_country: "US"
key_province: "NY"
key_city: "New York"
key_organisation: "EvilCorp"
key_mail: "evilcorp@foo.com"
key_ou: "evilcorp room"
key_size: 2048
