---
- name: VPN - Copy CA,certificates and keys in Openvpn server location
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_config_server_path }}"
    owner: root
    group: root
    mode: 0600
    remote_src: yes
  loop:
    - "{{ easy_rsa_pki_path }}/private/{{ openvpn_server_key }}"
    - "{{ easy_rsa_pki_path }}/issued/{{ openvpn_server_crt }}"
    - "{{ easy_rsa_pki_path }}/{{ openvpn_hmac_key }}"
    - "{{ easy_rsa_pki_path }}/{{ openvpn_ca }}"

- name: VPN - Copy template for openvpn server conf
  template:
    src: server.conf.j2
    dest: "{{ openvpn_base_path }}/server.conf"
    owner: root
    group: root
    mode: '0644'

- name: VPN - Enable IPv4 packet forwarding, reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: VPN - Start openvpn service and at boot too
  service:
    name: "openvpn@server.service"
    state: started
    enabled: yes

